// Product configuration (mirrors src/vietlott/config/products.py).
import type { ProductConfig, ProductName } from "./types";

export const PRODUCTS: Record<ProductName, ProductConfig> = {
  power_535: {
    name: "power_535",
    display: "Power 5/35",
    rawPath: "data/power535.jsonl",
    minValue: 1,
    maxValue: 35,
    sizeOutput: 5,
    hasSpecial: true,
    specialPosition: 5,
    specialPickRequired: true,
    specialMin: 1,
    specialMax: 12,
    specialCount: 12,
    steinerSystem: [2, 3, 35],
    ticketPrice: 10000,
  },
  power_645: {
    name: "power_645",
    display: "Power 6/45",
    rawPath: "data/power645.jsonl",
    minValue: 1,
    maxValue: 45,
    sizeOutput: 6,
    hasSpecial: false,
    specialPosition: 0,
    specialPickRequired: false,
    specialMin: 0,
    specialMax: 0,
    specialCount: 1,
    steinerSystem: [2, 3, 45],
    ticketPrice: 10000,
  },
  power_655: {
    name: "power_655",
    display: "Power 6/55",
    rawPath: "data/power655.jsonl",
    minValue: 1,
    maxValue: 55,
    sizeOutput: 6,
    hasSpecial: true,
    specialPosition: 6,
    specialPickRequired: false,
    specialMin: 1,
    specialMax: 55,
    specialCount: 1,
    steinerSystem: [2, 3, 55],
    ticketPrice: 10000,
  },
  keno: {
    name: "keno",
    display: "Keno",
    rawPath: "data/keno.jsonl",
    minValue: 1,
    maxValue: 45,
    sizeOutput: 6,
    hasSpecial: false,
    specialPosition: 0,
    specialPickRequired: false,
    specialMin: 0,
    specialMax: 0,
    specialCount: 1,
    steinerSystem: [2, 3, 45],
    ticketPrice: 10000,
  },
  "3d": {
    name: "3d",
    display: "Max 3D",
    rawPath: "data/3d.jsonl",
    minValue: 0,
    maxValue: 999,
    sizeOutput: 6,
    hasSpecial: false,
    specialPosition: 0,
    specialPickRequired: false,
    specialMin: 0,
    specialMax: 0,
    specialCount: 1,
    steinerSystem: [2, 3, 10],
    ticketPrice: 10000,
  },
  "3d_pro": {
    name: "3d_pro",
    display: "Max 3D Pro",
    rawPath: "data/3d_pro.jsonl",
    minValue: 0,
    maxValue: 999,
    sizeOutput: 6,
    hasSpecial: false,
    specialPosition: 0,
    specialPickRequired: false,
    specialMin: 0,
    specialMax: 0,
    specialCount: 1,
    steinerSystem: [2, 3, 10],
    ticketPrice: 10000,
  },
  bingo18: {
    name: "bingo18",
    display: "Bingo 18",
    rawPath: "data/bingo18.jsonl",
    minValue: 0,
    maxValue: 9,
    sizeOutput: 3,
    hasSpecial: false,
    specialPosition: 0,
    specialPickRequired: false,
    specialMin: 0,
    specialMax: 0,
    specialCount: 1,
    steinerSystem: [2, 3, 10],
    ticketPrice: 10000,
  },
};

export function getProduct(name: ProductName): ProductConfig {
  const cfg = PRODUCTS[name];
  if (!cfg) throw new Error(`Unknown product: ${name}`);
  return cfg;
}
