"""Deterministic low-discrepancy (rank-1 lattice) ticket generator.

Rationale
---------
All other generators in this package are either pseudorandom
(:class:`RandomModel`, AntiShare sampling) or heuristic ranked
(frequency, absence, Steiner, ...).  None is *space-filling and
deterministic* in the quasi-Monte-Carlo sense.  This strategy walks a
rank-1 lattice: successive tickets are the lattice points' ``k``
largest coordinates, so a batch of tickets spreads over the number
range far more evenly than an equal batch of pseudorandom tickets.

Implementation (standard library only)
--------------------------------------
A rank-1 (Kronecker) lattice in dimension ``M = max_val - min_val + 1``
is generated by the irrational vector ``alpha`` whose ``m``-th component
is the fractional part of ``sqrt(p_m)`` (``p_m`` = the ``m``-th prime).
Lattice point ``j`` is ``frac(j * alpha)`` (componentwise).  A ticket
maps a lattice point to ``k`` distinct numbers by choosing the indices
of its ``k`` largest coordinates: ``sorted(rank(frac)[-k:])``.

Honesty note on expected value
------------------------------
Deterministic does not mean predictable: the draw is still uniformly
random, so every ticket is equally likely and the expected value is the
same as uniform random tickets.  What changes is *batch uniformity* —
the tickets you buy cover the range more evenly across the batch — not
any edge in win probability.

Determinism
-----------
Tickets for a date start from a date-seeded offset and then advance one
lattice step per call, so a replay of the same date sequence reproduces
the same tickets and different dates land at different lattice phases.
"""

from __future__ import annotations

import math
import random

from machine_learning.strategies.base import PredictModel


def _first_primes(n: int) -> list[int]:
    """Return the first ``n`` primes (n <= 55, so the trial division is trivial)."""
    primes: list[int] = []
    candidate = 2
    while len(primes) < n:
        if all(candidate % p for p in primes):
            primes.append(candidate)
        candidate += 1
    return primes


class QuasiRandomStrategy(PredictModel):
    """Deterministic space-filling ticket generator built on a rank-1 lattice.

    Parameters
    ----------
    df:
        Historical lottery data.  Unused for number selection (the lattice
        is product-agnostic and uniform); kept for the ``PredictModel``
        contract.
    time_predict:
        Number of tickets generated per draw during backtesting.
    min_val, max_val:
        Inclusive number range.
    lookback_days:
        Contract-only parameter, accepted for registry consistency and
        ignored (the lattice never reads historical draws).
    """

    def __init__(
        self,
        df,
        time_predict: int = 1,
        min_val: int = PredictModel.POWER_655_MIN_VAL,
        max_val: int = PredictModel.POWER_655_MAX_VAL,
        lookback_days: int = 365,
    ):
        """Create the strategy; ``lookback_days`` is contract-only and unused."""
        super().__init__(df, time_predict=time_predict, min_val=min_val, max_val=max_val)
        self.lookback_days = int(lookback_days)
        self._alpha_cache: dict[int, list[float]] = {}
        self._call_counter: dict[tuple, int] = {}

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _pool_tag(pool: tuple[int, ...]) -> str:
        """Stable, hash-seed-independent signature for a pool."""
        return ",".join(str(n) for n in pool)

    def _alpha(self, dimension: int) -> list[float]:
        """Return the cached irrational generator vector for ``dimension``."""
        alpha = self._alpha_cache.get(dimension)
        if alpha is None:
            alpha = [math.sqrt(p) % 1.0 for p in _first_primes(dimension)]
            self._alpha_cache[dimension] = alpha
        return alpha

    def _offset(self, date, dimension: int) -> int:
        """Date-seeded lattice phase so different dates start elsewhere."""
        seed = f"quasirandom-offset|{date}|{self.min_val}|{self.max_val}|{self.number_predict}|{dimension}"
        return random.Random(seed).randrange(0, 10**9)

    # ------------------------------------------------------------------
    # Prediction
    # ------------------------------------------------------------------

    def predict(self, date=None, candidate_pool=None):
        """Return the next lattice ticket for ``date`` (deterministic per call order).

        Successive calls for the same date advance one lattice step and so
        return distinct space-filling tickets; a fresh instance replaying
        the same call sequence returns the same tickets.  When
        ``candidate_pool`` is given the lattice indices map onto the
        sorted pool and every output number stays inside it.  Raises
        ``ValueError`` when the pool is smaller than ``number_predict``.
        """
        if candidate_pool is not None:
            pool = tuple(sorted({int(n) for n in candidate_pool}))
            if len(pool) < self.number_predict:
                raise ValueError(f"candidate pool too small: {len(pool)} < {self.number_predict}")
        else:
            pool = tuple(range(self.min_val, self.max_val + 1))
            if len(pool) < self.number_predict:  # pragma: no cover - defensive
                raise ValueError(f"number range too small: {len(pool)} < {self.number_predict}")

        dimension = len(pool)
        alpha = self._alpha(dimension)
        counter_key = (
            str(date),
            self._pool_tag(pool),
            self.min_val,
            self.max_val,
            int(self.number_predict),
        )
        idx = self._call_counter.get(counter_key, 0)
        self._call_counter[counter_key] = idx + 1

        step = self._offset(date, dimension) + idx
        # Lattice point: frac(step * alpha); rank by coordinate, take the
        # indices of the k largest, sort them (ascending indices -> distinct
        # numbers).
        coords = [((step * a) % 1.0, m) for m, a in enumerate(alpha)]
        coords.sort(key=lambda pair: pair[0])
        chosen = sorted(m for _, m in coords[-int(self.number_predict) :])
        return [pool[m] for m in chosen]
